width_window = 1200
height_window = 700
mage_attack = 5
mage_cooldown = 1000 # скорость стрельбы мага
mage_repulsion = 0 #сила отталкивания мага
mage_slowdown = 1 #сила замедления мага
tower_health = 100 #жизни башни мага
FPS = 60
voloume_music = 0.06
monster_hp = 15
boss_hp = 50
mminmon = 1
mmaxmon = 3
bminmon = 10
bmaxmon = 30