width_window = 1200
height_window = 700
width_mage = 90
height_mage = 114
mage_attack = 1
mage_speed = 1 # скорость стрельбы мага
mage_repulsion = 0 #сила отталкивания мага
mage_slowdown = 1 #сила замедления мага
tower_health = 100 #жизни башни мага
